### ISSUE TITLE
Possible issue with newer OSX version

### ISSUE THREAD

**Issue by jonasschnelli** [al45tair/ds_store#4]
Bitcoin Core uses the ds_store module to generate a DMGs DS_Store (arrangement and background).
Newer macOS Versions (tested 10.12 and. 10.14) can't open the volume – containing the DS_Store. file – anymore (while older versions like 10.8 still can). Sometimes Finder even crashes.

The DMG in case someone likes to test this: 
https://bitcoincore.org/bin/bitcoin-core-0.17.0/bitcoin-0.17.0-osx.dmg

Removing the DS_Store file cures the issue.

**Comment by jonasschnelli** [comment]
Thanks @jakepetroules!
Closing.

**Comment by al45tair** [comment]
Perhaps worth mentioning that [dmgbuild](https://github.com/al45tair/dmgbuild) doesn't suffer from this problem - it definitely encodes the window bounds as a string (I just checked).

It's possible that we should consider adding some type checks to `ds_store` to prevent this kind of problem — though the downside of that is that it's equally possible that Apple in a future release of the macOS could choose to vary the set of valid representations for a given property, so these might have to be warnings rather than errors.
